apiVersion: v1
kind: Service
metadata:
  name: resut-service
  labels:
    name: resut-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    name: resut-app-pod
    app: demo-voting-app